# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Junho Lee
tagline:          
url:              https://palejelly.github.io/
paginate:         1
baseurl:          /
author:
  name:           Junho Lee
  url:            https://palejelly.github.io/
  email:          palejelly@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://palejelly.github.io/

pages_list:       
  About: '/about'
  Projects: '/projects'
  GitHub : 'https://github.com/palejelly'
  Else: '/else'
